# Config template for Ingenious projects
# This is a template file that will be copied to your project root as config.yml

profile: default
project:
  name: my_ingenious_project
  description: A new Ingenious framework project
  version: 0.1.0
web_configuration:
  ip_address: 0.0.0.0
  port: 80
  type: fastapi
  asynchronous: false
  authentication:
    enable: false
    username: ""
    password: ""
    type: ""
extensions:
  enabled: true
  paths:
    - ./extensions
providers:
  openai:
    api_key: ${OPENAI_API_KEY}
    organization: ${OPENAI_ORGANIZATION}
    # Uncomment to use Azure OpenAI
    # azure_endpoint: ${AZURE_OPENAI_ENDPOINT}
    # api_version: "2023-05-15"
    # deployment_name: ${AZURE_OPENAI_DEPLOYMENT_NAME}
models:
  - name: default
    model: gpt-4o
    api_key: ${OPENAI_API_KEY}
    base_url: ""
    api_type: "openai"
    api_version: "2023-05-15"
chat_history:
  database_type: "sqlite"
  database_path: "./tmp/high_level_logs.db"
  database_connection_string: ""
  database_name: ""
  memory_path: "./tmp"
chat_service:
  type: basic
chainlit_configuration:
  enable: false
  authentication:
    enable: false
    github_secret: ""
    github_client_id: ""
logging:
  log_level: INFO
  root_log_level: INFO
tool_service:
  enable: false
azure_search_services: []
azure_sql_services:
  database_connection_string: ""
  database_name: ""
  table_name: ""
local_sql_db:
  database_path: "/tmp/sample_sql_db"
  sample_csv_path: ""
  sample_database_name: "sample_sql_db"
file_storage:
  storage_type: "local"
  path: "./storage"
  revisions:
    storage_type: "local"
    path: "./revisions"
    add_sub_folders: true
    container_name: ""
    url: ""
    client_id: ""
    token: ""
    authentication_method: default_credential
    enable: true
  data:
    storage_type: "local"
    path: "./data"
    add_sub_folders: true
    container_name: ""
    url: ""
    client_id: ""
    token: ""
    authentication_method: default_credential
    enable: true
receiver_configuration:
  enable: true
  api_url: ""
  api_key: ""
