FROM mcr.microsoft.com/vscode/devcontainers/base:1-ubuntu-24.04

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apt update 
RUN apt install -y python3
RUN apt install -y python3-pip
RUN apt install -y python3.12-venv

RUN python3 -m venv .venv
#RUN . ./.venv/bin/activate && pip3 install -r ./installs/requirements.txt
RUN apt install -y  wget
RUN apt install zsh git fonts-font-awesome -y 
# RUN sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
#RUN . ./.venv/bin/activate && python3 -c "from transformers import AutoTokenizer, AutoModel; \
#           AutoTokenizer.from_pretrained('sentence-transformers/all-MiniLM-L6-v2'); \
#           AutoModel.from_pretrained('sentence-transformers/all-MiniLM-L6-v2')"
